### ISSUE TITLE
Support to create isolated branches using "checkout --orphan"

### ISSUE THREAD

**Issue by JaimeChavarriaga** [rherrmann/gonsole#51]
Currently, Gonsole does not support "checkout --orphan".

In Git, developers can create isolated branches where the history of the original branch is not copied into the new branch. This is used in Github, for instance, to create a branch for source code and another isolated "gh-pages" branch for a website.

In the Github Pages help, there is an explanation of the steps to create an empty branch using "checkout --orphan"
*  https://help.github.com/articles/creating-project-pages-manually/

According to the following link, JGit only supports "checkout --orphan" since beginning of 2014, but the EGit plugin does not use this option yet. There is a code snippet that may help to introduce this option into the Gonsole.
*   http://stackoverflow.com/questions/24653762/eclipse-new-empty-branch-creation

**Comment by rherrmann** [comment]
I've pushed a change to the JGit code review systen: https://git.eclipse.org/r/40808. that adds support for  `checkout --orphan` to the pgm component of JGit.
As soon as there is a JGit release that includes this change, it can be consumed by Gonsole.

**Comment by rherrmann** [comment]
The new version can either be installed from http://rherrmann.github.io/gonsole/repository/ or - if an older version is already installed - through _Help > Check for Updates_
