### ISSUE TITLE
add does not work

### ISSUE THREAD

**Issue by WTBenjamin** [rherrmann/gonsole#52]
I tried to add files to the index using the command:

add *

Unfortunately no files were added to the index!

(using gonsole v 1.1)

**Comment by rherrmann** [comment]
Gonsole uses [JGit](https://eclipse.org/jgit/) to execute the console commands and unfortunately JGit [does not yet support file globs](http://download.eclipse.org/jgit/site/3.7.0.201502260915-r/apidocs/org/eclipse/jgit/api/AddCommand.html#addFilepattern(java.lang.String)).

You can use `add .` instead to add all files in the work directory to the index.

Please re-open if you still have issues.
