### ISSUE TITLE
Gonsole EGit integration not installable on Eclipse Mars

### ISSUE THREAD

**Issue by urferr** [rherrmann/gonsole#53]
In Eclipse Mars JGit and EGit have Version number 4.0.0 which is not included in the bundle dependencies of the gonsole.egit manifest

 org.eclipse.egit.core;bundle-version="[1.3.0,4.0.0)", 
 org.eclipse.jgit;bundle-version="[3.6.0,4.0.0)"

**Comment by rherrmann** [comment]
Thanks a lot for pointing this out! Fixed with commit d595ff6b4eac3ef91e099a38c73884f988635a51.
