### ISSUE TITLE
Entering an empty command twice interrupts the REPL loop

### ISSUE THREAD

**Issue by Treehopper** [rherrmann/gonsole#54]
Reproducable: always, also with the "calc" console.
Simply hit enter twice, and you end up with this:
repo>
repo>
|

I did not find a way to recover from this, other than closing and re-opening the console.

**Comment by rherrmann** [comment]
Thanks for reporting this, I can reproduce the problem.

We are curently busy with [other things](http://www.codeaffine.com/2015/06/25/testing-with-junit-book-announcement/) / on vacation but will look into the issue as soon as we find the time.

**Comment by rherrmann** [comment]
Fixed with commit fad2c7c670fc97b4ab123fed6266005e4f539974. When the [new build has finished](https://travis-ci.org/rherrmann/gonsole/builds/80089602) it will be available from the update site http://rherrmann.github.io/gonsole/repository/

**Comment by Treehopper** [comment]
Great. Thanks for fixing this!
