### ISSUE TITLE
Unable to make it work on Mars.1 (4.5.1)

### ISSUE THREAD

**Issue by imeszaros** [rherrmann/gonsole#59]
Steps to reproduce:
- Download and extract: http://download.eclipse.org/eclipse/downloads/drops4/R-4.5.1-201509040015/download.php?dropFile=eclipse-platform-4.5.1-win32.zip
- Help -> Install New Software
  - Install EGit
  - Install Gonsole

After a restart, in the "Open Console" menu there is only "New Console View". Neither the preference page "Git Console" is showing up.

**Comment by rherrmann** [comment]
I followed the steps described (except that I used win32_64 since I don't have a 32-bit VM) and the Git Console is fully functional.
Which version and from where exactly did you install EGit and Gonsole?
Do you see the Gonsole logo in the about dialog?

I doubt that the 64-bit version of Eclipse is the reason since the Git Console has no platform dependant code.

**Comment by imeszaros** [comment]
Yes, the Gonsole logo is displayed in the about dialog.

The full content of my "Installation Details" looks like the following:

Name | Version | Id | Provider
-----|---------|----|---------
Eclipse Git Team Provider | 4.0.3.201509231615-r | org.eclipse.egit.feature.group | Eclipse EGit
Eclipse Git Team Provider - Gitflow support | 4.0.3.201509231615-r | org.eclipse.egit.gitflow.feature.feature.group | Eclipse EGit
Eclipse Git Team Provider - Task focused interface | 4.0.3.201509231615-r | org.eclipse.egit.mylyn.feature.group | Eclipse EGit
Eclipse GitHub integration with task focused interface | 4.0.3.201509231615-r | org.eclipse.mylyn.github.feature.feature.group | Eclipse EGit
Eclipse Platform | 4.5.1.M20150904-0015 | org.eclipse.platform.ide | Eclipse.org
Gonsole - EGit Integration | 1.1.0.20151125-1520 | com.codeaffine.gonsole.egit.feature.feature.group | codeaffine.com
Gonsole - Git Console for Eclipse | 1.1.0.20151125-1520 | com.codeaffine.gonsole.feature.feature.group | codeaffine.com

I installed EGit from Mars - http://download.eclipse.org/releases/mars/
and Gonsole from Gonsole Software Repository - http://rherrmann.github.io/gonsole/repository/

![gonsole](https://cloud.githubusercontent.com/assets/691942/11501681/5b78e5cc-9836-11e5-9a03-cb5ff6a9ddcd.png)

Unfortunately in this bare minimum setup i cannot open the error log view, but i have another installation and there i also cannot open Gonsole. Now i checked the error log view there and found the following:

![error](https://cloud.githubusercontent.com/assets/691942/11501785/1a0c45a6-9837-11e5-948a-73cc215782ca.PNG)

Java 8 is not currently supported?

**Comment by imeszaros** [comment]
Okay... sorry for being stupid, now I see on the Gonsole website that Java 8 is a requirement.

**Comment by rherrmann** [comment]
Glad you found the reason and I also hope you'll be able to upgrade your JRE to Java 8. We recently decided to move to Java 8: http://www.codeaffine.com/2015/10/08/gonsole-requirement-upgrade-to-jre-8/

However, I think Eclipse shouldn't let you install a feature if it cannot be run in the current environment...

**Comment by imeszaros** [comment]
Now i'm running on Java 8, Gonsole works fine. Thanks for your help!

**Comment by rherrmann** [comment]
For reference, I've opened this bug at Eclipse p2: [Installer should not allow to install features that can't run with the current JRE](https://bugs.eclipse.org/bugs/show_bug.cgi?id=483383)
