### ISSUE TITLE
Can't remove unstaged changes

### ISSUE THREAD

**Issue by evgeniy-storozhenko** [rherrmann/gonsole#61]
Can't remove unstaged changes:
```git checkout -- .```

It's very useful, when you want to do something with files that have the same extensions, location and other stuff.

<img width="1080" alt="screen shot 2016-01-11 at 15 16 14" src="https://cloud.githubusercontent.com/assets/6041943/12230050/3b876bc2-b86f-11e5-9a1e-6db5045c2697.png">

**Comment by rherrmann** [comment]
Gonsole does not execute the entered commands itself. Instead it forwards all commands to the [JGit CLI](https://wiki.eclipse.org/JGit/User_Guide#Running_the_JGit_CLI). Hence Gonsole is restricted to those commands supported by JGit.

If you are missing a feature please open a [JGit enhancement request](https://eclipse.org/jgit/support/). As soon as JGit provides a release with the new feature included, it will also be available in Gonsole.

**Comment by evgeniy-storozhenko** [comment]
Ok, thank you.
