### ISSUE TITLE
Eclipse doesn't allow to open gonsole after installation and restart

### ISSUE THREAD

**Issue by nshavitt** [rherrmann/gonsole#66]
I just installed the plugin but after restart of eclipse, trying to open the gonsole console , I failed because I didn't get it as an option in the new console menu.

**Comment by fappel** [comment]
Could you please post your system information (Java Version, Eclipse Version, OS Version) and check if there are any log entries in the Error log available? This might ease to find the problem's cause. In any case, take care that you're using a Java 8 VM since older versions are not supported.

**Comment by nshavitt** [comment]
Version: Luna SR2 (4.4.2)
Build id: M20150204-1700
java version "1.7.0_45"

**Comment by fappel** [comment]
Ok, it seems as if your Java version is too old. Gonsole needs 1.8.0 or newer. See also https://github.com/rherrmann/gonsole/issues/59 and the requirements section on http://rherrmann.github.io/gonsole/.

**Comment by rherrmann** [comment]
Closing this issue as it seems to be resolved. @nshavitt, please re-open with further information if you still experience problems.

**Comment by bsolino** [comment]
I'm having the same issue, but my Eclipse and Java versions are more modern:
OS: Microsoft Windows 8.1
Eclipse:
    Version: Neon.3 Release (4.6.3)
    Build id: 20170314-1500
Java:
    java version "1.8.0_131"
    Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by rherrmann** [comment]
@bsolino the environment that you list should work. Do you see any related messages in the _Error Log_ view or during installation? Please also make sure that gonsole is shown in the about dialog.
