### ISSUE TITLE
Where is stash command ?

### ISSUE THREAD

**Issue by aleksbenmaza** [rherrmann/gonsole#80]
`MyRepo> git stash list`
`Unrecognized command: stash`

How come this command does not exist ?

**Comment by rherrmann** [comment]
Gonsole uses JGit, a pure Java implementation of Git, to access repositories. JGit's command interpreter does not yet know the `stash` command.

The way to have a `stash` command in Gonsole would be to open a feature request with JGit and kindly ask to implement the stash command in their 'pgm' module. Once this is implemented, it will also be available in Gonsole.
